global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "auth-service"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["auth-service:8000"]
        labels:
          service: "auth-service"

  - job_name: "profile-service"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["profile-service:8000"]
        labels:
          service: "profile-service"

  - job_name: "jobs-service"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["jobs-service:8000"]
        labels:
          service: "jobs-service"

  - job_name: "applications-service"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["applications-service:8000"]
        labels:
          service: "applications-service"

  - job_name: "reviews-service"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["reviews-service:8000"]
        labels:
          service: "reviews-service"

  - job_name: "mailing-service"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["mailing-service:8000"]
        labels:
          service: "mailing-service"

  - job_name: "verification-service"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["verification-service:8000"]
        labels:
          service: "verification-service"

  - job_name: "notifications-service"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["notifications-service:8000"]
        labels:
          service: "notifications-service"
